
/* Coder .h file for system Model */
/* Program generated by Cadvanced 4.3.0  */
#define XSCT_CADVANCED


extern tSDLTypeInfo ySDL_SignalId;
extern tSDLSignalInfo ySDL_FinishSimulation;
extern tSDLSignalInfo ySDL_OrderSpeedRequest;
extern tSDLSignalInfo ySDL_OrderTurnRequest;
extern tSDLSignalInfo ySDL_OrderFireRequest;
extern tSDLSignalInfo ySDL_InitDataComplete;
extern tSDLSignalInfo ySDL_StartSimulation;
extern tSDLSignalInfo ySDL_DestroyShip;
extern tSDLSignalInfo ySDL_OrderSpeedResponse;
extern tSDLSignalInfo ySDL_OrderSpeedReject;
extern tSDLSignalInfo ySDL_OrderTurnResponse;
extern tSDLSignalInfo ySDL_OrderTurnReject;
extern tSDLSignalInfo ySDL_OrderFireResponse;
extern tSDLSignalInfo ySDL_OrderFireReject;
extern tSDLSignalInfo ySDL_ShipsCurrentState;
extern tSDLSignalInfo ySDL_VisibleShip;
extern tSDLSignalInfo ySDL_StrategyVictory;
extern tSDLSignalInfo ySDL_StrategyLose;
extern tSDLSignalInfo ySDL_messageLog;
extern tSDLSignalInfo ySDL_messageError;

extern tSDLSignalInfo * xSignalList[];
extern xSignalIdNode xSignalIdList[];
