
/* SKELETON for env functions */
/* Program generated by Cadvanced 4.3.0  */
#define XSCT_CADVANCED

#define SCT_VERSION_4_3
#include "scttypes.h"
#ifdef XINCLUDE_HS_FILE
#include "Model.hs"
#endif
#ifdef XENV_INC
#include XENV_INC
#endif
#include "Model.ifc"
#include "cucf.h"
#include "Model_cod.h"
#include "cucf.h"

#ifndef XENV_BUF
#define XENV_BUF(stmt) stmt
#endif

#ifndef XENV_STATIC_VARS
#define XENV_STATIC_VARS static tBuffer Buf = 0;
#endif
XENV_STATIC_VARS


#ifndef XNOGLOBALNODENUMBER
/*---+---------------------------------------------------------------
     xGlobalNodeNumber  extern
-------------------------------------------------------------------*/
#ifndef XENV_NODENUMBER
#define XENV_NODENUMBER return 1;
#endif

extern int xGlobalNodeNumber(void)
{
  /* Assign a unique global system Id to each SDL system in a cluster of systems. */
  XENV_NODENUMBER
}
#endif


#ifndef XNOINITENV
/*---+---------------------------------------------------------------
     xInitEnv  extern
-------------------------------------------------------------------*/
#ifndef XENV_INIT
#define XENV_INIT BufInitBuf(Buf, bms_SmallBuffer);
#endif

extern void xInitEnv(void)
{
  /* Code to initialize your SDL-system environment may be inserted here */
  XENV_INIT

#ifdef XTRACE
  xPrintString("xInitEnv called\n");
#endif
}
#endif


#ifndef XNOCLOSEENV
/*---+---------------------------------------------------------------
     xCloseEnv  extern
-------------------------------------------------------------------*/
#ifndef XENV_CLOSE
#define XENV_CLOSE BufCloseBuf(Buf);
#endif

extern void xCloseEnv(void)
{
  /* Code to bring down the environment in a controlled manner
     may be inserted here. */
  XENV_CLOSE

#ifdef XTRACE
  xPrintString("xCloseEnv called\n");
#endif
}
#endif


/*---+---------------------------------------------------------------
     Macros for xOutEnv
-------------------------------------------------------------------*/
#ifndef OUT_LOCAL_VARIABLES
#define OUT_LOCAL_VARIABLES
#endif

#ifndef IF_OUT_SIGNAL
#define IF_OUT_SIGNAL(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  if (((*SignalOut)->NameNode) == SIGNAL_NAME) {
#define END_IF_OUT_SIGNAL(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  }
#endif

#ifndef OUT_SIGNAL1
#define OUT_SIGNAL1(SIGNAL_NAME, SIGNAL_NAME_STRING)
#endif

#ifndef OUT_SIGNAL2
#define OUT_SIGNAL2(SIGNAL_NAME, SIGNAL_NAME_STRING)
#endif

#ifndef XENV_ENC
#define XENV_ENC(stmt) stmt
#endif

#ifndef XENV_OUT_START
#define XENV_OUT_START
#endif

#ifndef RELEASE_SIGNAL
#define RELEASE_SIGNAL   xReleaseSignal(SignalOut); return;
#endif


/*---+---------------------------------------------------------------
     xOutEnv  extern
-------------------------------------------------------------------*/
extern void xOutEnv( xSignalNode *SignalOut )
{
  OUT_LOCAL_VARIABLES

#ifdef XTRACE
#ifdef XIDNAMES
  char  Temp[100];
  sprintf(Temp, "xOutEnv:  %s has been received by env\n",
          (*SignalOut)->NameNode->Name );
  xPrintString(Temp);
#else
  xPrintString("xOutEnv:  One signal has been received by env\n");
#endif
#endif

  XENV_OUT_START


  /* Signals going to the env via the channel StSimInt */

    /* Signal FinishSimulation */
    IF_OUT_SIGNAL(FinishSimulation,"FinishSimulation")
      OUT_SIGNAL1(FinishSimulation,"FinishSimulation")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_SDL_Integer,
        (void *)&((yPDef_FinishSimulation *)(*SignalOut))->Param1));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
        (void *)&((yPDef_FinishSimulation *)(*SignalOut))->Param2));
      OUT_SIGNAL2(FinishSimulation,"FinishSimulation")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(FinishSimulation,"FinishSimulation")

    /* Signal OrderSpeedRequest */
    IF_OUT_SIGNAL(OrderSpeedRequest,"OrderSpeedRequest")
      OUT_SIGNAL1(OrderSpeedRequest,"OrderSpeedRequest")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
        (void *)&((yPDef_OrderSpeedRequest *)(*SignalOut))->Param1));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
        (void *)&((yPDef_OrderSpeedRequest *)(*SignalOut))->Param2));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_1J_tFactorAcceleration,
        (void *)&((yPDef_OrderSpeedRequest *)(*SignalOut))->Param3));
      OUT_SIGNAL2(OrderSpeedRequest,"OrderSpeedRequest")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(OrderSpeedRequest,"OrderSpeedRequest")

    /* Signal OrderTurnRequest */
    IF_OUT_SIGNAL(OrderTurnRequest,"OrderTurnRequest")
      OUT_SIGNAL1(OrderTurnRequest,"OrderTurnRequest")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
        (void *)&((yPDef_OrderTurnRequest *)(*SignalOut))->Param1));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
        (void *)&((yPDef_OrderTurnRequest *)(*SignalOut))->Param2));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_0V_tHeadingChange,
        (void *)&((yPDef_OrderTurnRequest *)(*SignalOut))->Param3));
      OUT_SIGNAL2(OrderTurnRequest,"OrderTurnRequest")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(OrderTurnRequest,"OrderTurnRequest")

    /* Signal OrderFireRequest */
    IF_OUT_SIGNAL(OrderFireRequest,"OrderFireRequest")
      OUT_SIGNAL1(OrderFireRequest,"OrderFireRequest")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
        (void *)&((yPDef_OrderFireRequest *)(*SignalOut))->Param1));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
        (void *)&((yPDef_OrderFireRequest *)(*SignalOut))->Param2));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_0T_tNameWeaponry,
        (void *)&((yPDef_OrderFireRequest *)(*SignalOut))->Param3));
      XENV_ENC(ASCIIEncode(Buf,
        (tSDLTypeInfo *)&ySDL_z_BasicTypes_17_tStringShotsList,
        (void *)&((yPDef_OrderFireRequest *)(*SignalOut))->Param4));
      OUT_SIGNAL2(OrderFireRequest,"OrderFireRequest")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(OrderFireRequest,"OrderFireRequest")

  /* Signals going to the env via the channel StMsgInt */

    /* Signal messageLog */
    IF_OUT_SIGNAL(messageLog,"messageLog")
      OUT_SIGNAL1(messageLog,"messageLog")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_SDL_Charstring,
        (void *)&((yPDef_messageLog *)(*SignalOut))->Param1));
      OUT_SIGNAL2(messageLog,"messageLog")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(messageLog,"messageLog")

    /* Signal messageError */
    IF_OUT_SIGNAL(messageError,"messageError")
      OUT_SIGNAL1(messageError,"messageError")
      XENV_BUF(BufInitWriteMode(Buf));
      XENV_ENC(ASCIIEncode(Buf, (tSDLTypeInfo *)&ySDL_SDL_Charstring,
        (void *)&((yPDef_messageError *)(*SignalOut))->Param1));
      OUT_SIGNAL2(messageError,"messageError")
      XENV_BUF(BufCloseWriteMode(Buf));
      RELEASE_SIGNAL
    END_IF_OUT_SIGNAL(messageError,"messageError")
}


/*---+---------------------------------------------------------------
     Macros for xInEnv
-------------------------------------------------------------------*/
#ifndef IN_LOCAL_VARIABLES
#define IN_LOCAL_VARIABLES \
  xSignalNode SignalIn;
#endif

#ifndef IN_SIGNAL1
#define IN_SIGNAL1(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  SignalIn = xGetSignal(SIGNAL_NAME, xNotDefPId, xEnv);
#endif

#ifndef IN_SIGNAL2
#define IN_SIGNAL2(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  SDL_Output(SignalIn xSigPrioPar(xDefaultSignalPrio), (xIdNode *)0);
#endif

#ifndef IF_IN_SIGNAL
#define IF_IN_SIGNAL(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  if (TEST_IF_IN_SIGNAL(SIGNAL_NAME)) {
#define END_IF_IN_SIGNAL(SIGNAL_NAME, SIGNAL_NAME_STRING) \
  }
#endif

#ifndef TEST_IF_IN_SIGNAL
#define TEST_IF_IN_SIGNAL(SIGNAL_NAME)  0
#endif

#ifndef XENV_DEC
#define XENV_DEC(stmt) stmt
#endif

#ifndef XENV_IN_START
#define XENV_IN_START
#endif

#ifndef XENV_IN_END
#define XENV_IN_END
#endif


/*---+---------------------------------------------------------------
     xInEnv  extern
-------------------------------------------------------------------*/
#ifndef XTENV
extern void xInEnv ( SDL_Time Time_for_next_event )
#else
extern SDL_Duration xInEnv ( SDL_Time Time_for_next_event )
#endif
{
  IN_LOCAL_VARIABLES

#ifdef XTRACE
#ifndef XNOXINENVTRACE
  xPrintString( "xInEnv: Called!\n");
#endif
#endif

  XENV_IN_START

  /* Signals comming from the env via the channel StSimInt */

  /* Signal InitDataComplete */
  IF_IN_SIGNAL(InitDataComplete,"InitDataComplete")
    IN_SIGNAL1(InitDataComplete,"InitDataComplete")
    IN_SIGNAL2(InitDataComplete,"InitDataComplete")
  END_IF_IN_SIGNAL(InitDataComplete,"InitDataComplete")

  /* Signal StartSimulation */
  IF_IN_SIGNAL(StartSimulation,"StartSimulation")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(StartSimulation,"StartSimulation")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_SDL_Integer,
      (void *)&((yPDef_StartSimulation *)SignalIn)->Param1));
    IN_SIGNAL2(StartSimulation,"StartSimulation")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(StartSimulation,"StartSimulation")

  /* Signal DestroyShip */
  IF_IN_SIGNAL(DestroyShip,"DestroyShip")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(DestroyShip,"DestroyShip")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_DestroyShip *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_DestroyShip *)SignalIn)->Param2));
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_0U_tNameShip,
      (void *)&((yPDef_DestroyShip *)SignalIn)->Param3));
    IN_SIGNAL2(DestroyShip,"DestroyShip")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(DestroyShip,"DestroyShip")

  /* Signal OrderSpeedResponse */
  IF_IN_SIGNAL(OrderSpeedResponse,"OrderSpeedResponse")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderSpeedResponse,"OrderSpeedResponse")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderSpeedResponse *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderSpeedResponse *)SignalIn)->Param2));
    IN_SIGNAL2(OrderSpeedResponse,"OrderSpeedResponse")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderSpeedResponse,"OrderSpeedResponse")

  /* Signal OrderSpeedReject */
  IF_IN_SIGNAL(OrderSpeedReject,"OrderSpeedReject")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderSpeedReject,"OrderSpeedReject")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderSpeedReject *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderSpeedReject *)SignalIn)->Param2));
    IN_SIGNAL2(OrderSpeedReject,"OrderSpeedReject")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderSpeedReject,"OrderSpeedReject")

  /* Signal OrderTurnResponse */
  IF_IN_SIGNAL(OrderTurnResponse,"OrderTurnResponse")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderTurnResponse,"OrderTurnResponse")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderTurnResponse *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderTurnResponse *)SignalIn)->Param2));
    IN_SIGNAL2(OrderTurnResponse,"OrderTurnResponse")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderTurnResponse,"OrderTurnResponse")

  /* Signal OrderTurnReject */
  IF_IN_SIGNAL(OrderTurnReject,"OrderTurnReject")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderTurnReject,"OrderTurnReject")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderTurnReject *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderTurnReject *)SignalIn)->Param2));
    IN_SIGNAL2(OrderTurnReject,"OrderTurnReject")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderTurnReject,"OrderTurnReject")

  /* Signal OrderFireResponse */
  IF_IN_SIGNAL(OrderFireResponse,"OrderFireResponse")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderFireResponse,"OrderFireResponse")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderFireResponse *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderFireResponse *)SignalIn)->Param2));
    IN_SIGNAL2(OrderFireResponse,"OrderFireResponse")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderFireResponse,"OrderFireResponse")

  /* Signal OrderFireReject */
  IF_IN_SIGNAL(OrderFireReject,"OrderFireReject")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(OrderFireReject,"OrderFireReject")
    XENV_DEC(ASCIIDecode(Buf, (tSDLTypeInfo *)&ySDL_z_BasicTypes_1K_tShipId,
      (void *)&((yPDef_OrderFireReject *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_OrderFireReject *)SignalIn)->Param2));
    IN_SIGNAL2(OrderFireReject,"OrderFireReject")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(OrderFireReject,"OrderFireReject")

  /* Signal ShipsCurrentState */
  IF_IN_SIGNAL(ShipsCurrentState,"ShipsCurrentState")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(ShipsCurrentState,"ShipsCurrentState")
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_ShipsCurrentState *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_15_tStringShipCurrentState,
      (void *)&((yPDef_ShipsCurrentState *)SignalIn)->Param2));
    IN_SIGNAL2(ShipsCurrentState,"ShipsCurrentState")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(ShipsCurrentState,"ShipsCurrentState")

  /* Signal VisibleShip */
  IF_IN_SIGNAL(VisibleShip,"VisibleShip")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(VisibleShip,"VisibleShip")
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_VisibleShip *)SignalIn)->Param1));
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_16_tStringEnemyShip,
      (void *)&((yPDef_VisibleShip *)SignalIn)->Param2));
    IN_SIGNAL2(VisibleShip,"VisibleShip")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(VisibleShip,"VisibleShip")

  /* Signal StrategyVictory */
  IF_IN_SIGNAL(StrategyVictory,"StrategyVictory")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(StrategyVictory,"StrategyVictory")
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_StrategyVictory *)SignalIn)->Param1));
    IN_SIGNAL2(StrategyVictory,"StrategyVictory")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(StrategyVictory,"StrategyVictory")

  /* Signal StrategyLose */
  IF_IN_SIGNAL(StrategyLose,"StrategyLose")
    XENV_BUF(BufInitReadMode(Buf));
    IN_SIGNAL1(StrategyLose,"StrategyLose")
    XENV_DEC(ASCIIDecode(Buf,
      (tSDLTypeInfo *)&ySDL_z_BasicTypes_1L_tStrategyId,
      (void *)&((yPDef_StrategyLose *)SignalIn)->Param1));
    IN_SIGNAL2(StrategyLose,"StrategyLose")
    XENV_BUF(BufCloseReadMode(Buf));
  END_IF_IN_SIGNAL(StrategyLose,"StrategyLose")

  XENV_IN_END

#ifdef XTENV
  return SDL_Time_Lit((xint32)0,(xint32)0);
#endif

}
